# Generated by Django 5.0.6 on 2024-06-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_employee_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
