# Generated by Django 5.0.6 on 2024-06-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
    ]
